# Generated by Django 3.2.2 on 2021-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_pastline_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastline',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
